name: build and deploy mathlib4 docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *' # every 8 hours
jobs:
  build:
    name: build and deploy mathlib4 docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: generate and deploy docs
        if: github.repository == 'leanprover/doc-gen4'
        run: |
          cd ../
          ./doc-gen4/deploy_docs.sh
        env:
          MATHLIB4_DOCS_KEY: ${{ secrets.MATHLIB4_DOCS_KEY }}
          DOC_GEN_REF: ${{ github.sha }}
